import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { CreateNoteModal } from "~/components/CreateNoteModal";
import { LoadingPage } from "~/components/LoadingSpinner";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const router = useRouter();
  const { isSignedIn, isLoaded } = useUser();
  const [isCreateNoteModalOpen, setIsCreateNoteModalOpen] = useState(false);

  const { data: notesData, isFetching: isFetchingNotes } =
    api.note.getAll.useQuery();

  useEffect(() => {
    if (!isSignedIn) {
      void router.push("/sign-up");
    }
  }, [isSignedIn, router]);

  if (!isLoaded || (isFetchingNotes && !notesData)) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Jot It</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-4 flex flex-col">
        {!notesData?.length ? (
          <div>No data :/</div>
        ) : (
          <div className="grid grid-cols-fill-xs gap-3">
            {notesData.map((note) => (
              <div
                key={note.id}
                className="rounded-lg border border-t-8 border-yellow-400 bg-white p-2"
              >
                <div className="line-clamp-6">{note.content}</div>
              </div>
            ))}
          </div>
        )}

        <button
          className="rounded-md bg-yellow-300 p-2 text-black"
          onClick={() => {
            setIsCreateNoteModalOpen(true);
          }}
        >
          Create note
        </button>

        <CreateNoteModal
          isOpen={isCreateNoteModalOpen}
          onClose={() => {
            setIsCreateNoteModalOpen(false);
          }}
        />
      </main>
    </>
  );
};

export default Home;
